language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mysql_5_6
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_mysql"
        - DB=mysql_5_6
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mysql_5.7
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_mysql"
        - DB=mysql_5.7
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.3
      addons:
        postgresql: '9.3'
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.3
      addons:
        postgresql: '9.3'
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.4
      addons:
        postgresql: '9.4'
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.4
      addons:
        postgresql: '9.4'
    - php: 7.1
      dist: trusty
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.5
      addons:
        postgresql: '9.5'
    - php: 7.1
      dist: trusty
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_pgsql"
        - DB=postgres_9.5
      addons:
postgresql: '9.5'

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - if [[ $DB == 'mysql_5.7' ]]; then bash .travis.install-mysql-5.7.sh; fi
  - if [[ $DRIVER == 'pdo_mysql' ]]; then mysql -e 'create database snapshot_tests;'; fi
  - if [[ $DRIVER == 'pdo_pgsql' ]]; then psql -c 'create database snapshot_tests;' -U postgres; fi
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - cp phpunit.xml.$DRIVER phpunit.xml
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
